version: '3.8'

services:
    front_end:
        image: frontend
        container_name: frontend
        ports:
          - 5000:5000
        command: ["serve", "-s", "-l", "5000", "build"]

    back_end:
        image: backend
        container_name: backend
        ports:
          - 8080:8080
        command: ["./server"]